### PR TITLE
fix(pre-commit-hooks)!: allow empty ranges in 'commitizen-branch'

### PR DESCRIPTION
**Pull request by AdrianDC**
## Description

**fix(pre-commit-hooks)!: move 'check' to 'args' for global options**

Details: 'args: [...]' is not able to access '-nr NO_RAISE' global
         arguments for example from a arguments configuration

**fix(pre-commit-hooks)!: allow empty ranges in 'commitizen-branch'**

Details: Pushing the same history from 'develop' to 'staging' for
         example fails because range 'origin/HEAD..HEAD' is empty
> No commit found with range: 'origin/HEAD..HEAD'

## Checklist

- [ ] Add test cases to all the changes you introduce
- [ ] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

## Expected behavior

Error `No commit found with range: 'origin/HEAD..HEAD'` not raised

## Steps to Test This Pull Request

Push same history to develop then staging

### CODE REVIEW

**Review by woile — COMMENTED** [review]
@Lee-W thoughts on this? LGTM

**Comment by Lee-W** [comment]
Looks good to me. but we probably won't want to bump a major version for it. so I would suggest we remove the ! in all the commits

**Comment by AdrianDC** [comment]
Thanks for the feedback.

IMO this should be a ! change, as any user having `args: []` as I used to will have local and CI breakages.

Could go along other fixes such as #1206 and #1207

**Example local usage until released:** https://gitlab.com/RadianDevCore/tools/gcil/-/blob/53e6cb534ff77704ac9b9dc51d755b9965556910/.pre-commit-config.yaml#L54

**Comment by Lee-W** [comment]
If that's the case, we'll need to wait for our next release. @woile we probably can create a v4 branch already?

**Review by Lee-W — APPROVED** [review]

**Comment by Lee-W** [comment]
Just change the base to v4. and let's merge it 🚀

**Pull request merged**
