### PR TITLE
refactor: set default_install_hook_types

### PR DESCRIPTION
**Pull request by 12rambau**
## Description
Since pre-commit 2.18.0, it is possible to tell pre-commit which hook to install directly from the .pre-commit-config.yaml file. Thus I update the said file to apply the hooks according to the docs: `pre-commit install -t pre-commit -t pre-push -t commit-msg`. I also updated the pre-commit version to make sure this parameter is available and finally updated the contributing documentation to make sure people simply use the `pre-commit install`command.

bonus: there was a typo that I corrected (it's "stageS")

## Checklist

- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the change

### CODE REVIEW

**Comment by 12rambau** [comment]
it needs https://github.com/commitizen-tools/commitizen/issues/607 to be solved first as this requires at least 3.7

**Comment by woile** [comment]
Could you point this PR to v3 branch?

**Comment by 12rambau** [comment]
> Thanks for the PR! Could you point this PR to `v3` branch? because of the 3.7 dep

done

**Comment by woile** [comment]
Would you mind rebasing on top of `v3`? Thanks!

**Comment by 12rambau** [comment]
isn't it already the case ?

**Comment by woile** [comment]
No, `v3` was merged, you can see all kind of unrelated commits in the list.

You can follow this instructions to rebase:

https://github.com/commitizen-tools/commitizen/pull/686#issuecomment-1512734865

**Comment by 12rambau** [comment]
sorry I'm used to work in repositories where we squash merge PR so this is not considered as an issue. I'll do another PR that will be easier considering the very few modifications I made

**Comment by 12rambau** [comment]
not sure I did the right thing but THB it's a super small modifcation. merge squash it it wil make everyone's life easier.

Also the PR will look strange but upon merging, git resolves the duplicates commits (as they have the same hash) so why rebasing ?

**Review by Lee-W — APPROVED** [review]

**Review by Lee-W — APPROVED** [review]
Thanks @12rambau . This looks great! 

@woile I'm planning on merging this one today.

**Pull request merged**
