### PR TITLE
Add Unicode Support

### PR DESCRIPTION
**Pull request by adam-grant-hendry**
Adds unicode support by allowing configurable encodings to be specified (defaults to `utf-8`).

## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

Fixes: Issue #516

### CODE REVIEW

**Comment by adam-grant-hendry** [comment]
@Lee-W @woile Please review at your earliest convenience. Thank you.

**Comment by Lee-W** [comment]
If I'm not mistaken, some of the changes are from https://github.com/commitizen-tools/commitizen/pull/605. If that's the case, I'll review it after that one is merged and rebased to this. I browsed through this PR. I think we should be able to merge it soon as well :)

**Comment by Lee-W** [comment]
Hi @adam-grant-hendry , we've merged #605 . feel free to rebase this one when you have time. thanks!

**Comment by adam-grant-hendry** [comment]
@Lee-W @woile I'm having trouble rebasing, so I'm moving this to #629

**Pull request closed without merging**
