### PR TITLE
ci(github-actions): add "3.13-dev" to Python tests (#1145)

### LINKED ISSUE #1145: Add python3.13 beta to github actions for testing
### Description

as title

### Possible Solution

_No response_

### Additional context

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by jakob-keller**
## Checklist

- [ ] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [ ] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

## Expected behavior

GitHub Actions will run tests for Python 3.13 (dev).

## Additional context

closes #1145

### CODE REVIEW

**Comment by jakob-keller** [comment]
Looks like there are currently incompatibilities with `cffi` under Python 3.13: https://github.com/python-cffi/cffi/issues/77 We will need to await their next release which is imminent.

**Comment by Lee-W** [comment]
looks like they've got it resolved. but rebasing doesn't seem to work still

**Comment by jakob-keller** [comment]
> looks like they've got it resolved. but rebasing doesn't seem to work still

Apparently it was fixed, but the release is still pending.

**Comment by jakob-keller** [comment]
`cffi==1.17.0` has been released, which helps a lot.

It turns out that Python 3.13 modifies the behaviour of `argparse --help`: https://github.com/python/cpython/pull/103372. I have updated tests accordingly. Please let me know, if we need to keep the tests for Python 3.12 and earlier.

Now there is only one issue left that is related to the removal of `pipes` in Python 3.13.

**Review by Lee-W — APPROVED** [review]
I'm a bit hesitant about whether we should use version 3.13 or below. However, since this is not a critical test, I think we should be fine.

**Comment by Lee-W** [comment]
I'll keep it open for a few days. cc @woile @noirbizarre

**Pull request merged**
