### PR TITLE
feat: draft of the --empty parameter

### LINKED ISSUE #662: create a dev bump straight after a normal bump
### Description

In projects I'm working in (the ones that are not yet using `commitizen`) maintainers are bumping a dev version straight after the bump of a new one. That ensures that the version number of the current master/main branch is not the same as the latest release. 

I wanted to use the new `--devrelease` option of the `bump` command for that purpose but as there are no changes to report since the last version, it's not working and the bump fail.

Do you think it would be doable or is it a workflow that you don't want to cover? 

### Steps to reproduce

```
cz bump
cz bump --devrelease 0
```

### Current behavior

bump fails

### Desired behavior

bump succeed (bonus point if nothing is written to the changelog file)

### Screenshots

_No response_

### Environment

cz version: master (as I still have an issue with my name convention and didn't find the time to work on #463)

### PR DESCRIPTION
**Pull request by 12rambau**
## Description

First draft of a new feature. The idea is to grant the user the capability to run `cz bump` without prior commits. The reasons are described in the associated issue. 

here we add an `--empty` parameter to the bump method
when this parameter is set and if no increment is find, a automatic "PATCH" is released. 

I'll wait for your feedback before working on tests and documentation.

## Checklist

- [ ] Add test cases to all the changes you introduce
- [ ] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [ ] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

## Additional context
Fix #662

### CODE REVIEW

**Comment by 12rambau** [comment]
any specific reason why this PR was removed ? is the  `--empty` parameter a no-go ?

**Comment by woile** [comment]
I apologize, I don't know why it was closed (and it doesn't let me open it again). Please feel free to open a new one

**Comment by 12rambau** [comment]
Let me base it directly on v3 it will everyone's life easier

**Comment by woile** [comment]
Everything is in master again, open a new pr to master (which has V3 now)

**Pull request closed without merging**
