### PR TITLE
Add yaml support for config

### PR DESCRIPTION
**Pull request by danvergara**
## Description

As mentioned in #314 , this PR add yaml support for configuration

## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./script/format` and `./script/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

## Expected behavior

Replace a TOML config file with a YAML config file with no side effects, (of course, passing the same arguments).

## Steps to Test This Pull Request

1. Run the tests
2. Activate the virtual environment provided by the project/Poetry
3. Since the yaml files are supported for configuration, try to add a new file called .cz.yaml or cz.yaml to customize Commitizen.

## Additional context

Related to #314

### CODE REVIEW

**Comment by Woile** [comment]
Mmmm I'm not a big fan of `yaml`. I don't want  to support a format that is kind of weird :sweat_smile: 
What do you think @Lee-W ?

**Comment by danvergara** [comment]
Hi @Woile. I'm adding this, because my team (golang developers) ask edfor this. As Go developers we are more familiar with `yaml`. But it's ok,  just let me know and I can address another issue.

**Comment by Lee-W** [comment]
> Mmmm I'm not a big fan of `yaml`. I don't want to support a format that is kind of weird 😅
> What do you think @Lee-W ?

I'm neutral to this. I did not use YAML that much. But one of my friends (Golang developer as well haha) did ask me whether we'll have YAML support.

**Comment by Woile** [comment]
Nice, okay then there's at least some demand.
@danvergara I'll ask you to squash the commits into just a `feat`, something like `feat: add yaml as a config option`. 
Otherwise I can do it, just let me know.

Thanks for the contribution :tada:

**Comment by danvergara** [comment]
@Woile sure, I can do that.

**Pull request merged**
