### PR TITLE
feat(ci/cd): automates the generation of CLI screenshots

### PR DESCRIPTION
**Pull request by marcosdotme**
## Checklist

- [ ] Add test cases to all the changes you introduce **_(not applicable)_**
- [ ] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test **_(not applicable)_**
- [x] Test the changes on the local machine manually
- [ ] Update the documentation for the changes **_(not applicable)_**

## Expected behavior
After any pull requested merged, this Github Action Workflow will be triggered and will updated the CLI screenshots.

## Steps to Test This Pull Request
I tested manually using an clone of **commitizen** repo.

General view:

image

Generate CLI screenshots using the **scripts/gen_cli_help_screenshots.py**:

image

Push updated images to repository:

image

### CODE REVIEW

**Comment by woile** [comment]
Wow nice! LGTM, @Lee-W ?

**Review by Lee-W — APPROVED** [review]
LGTM. Thanks!

**Comment by Lee-W** [comment]
Closes: #1112

**Comment by Lee-W** [comment]
ah... I forget to check the commit message. this should be `ci(..)` instead

**Comment by marcosdotme** [comment]
> ah... I forget to check the commit message. this should be `ci(..)` instead

Sure! I can rebase/ammend this. Any suggestions about the scope?

**Comment by marcosdotme** [comment]
Ops, it got merged already. Sorry for that! @Lee-W

**Comment by Lee-W** [comment]
> Ops, it got merged already. Sorry for that! @Lee-W

Yes, I suppose I wasn't actually awake. 🤦‍♂️

But after a second thought, we probably should move it to https://github.com/commitizen-tools/commitizen/blob/master/.github/workflows/docspublish.yml. otherwise, we might update the image without having them in the doc

**Comment by marcosdotme** [comment]
> > Ops, it got merged already. Sorry for that! @Lee-W
> 
> Yes, I suppose I wasn't actually awake. 🤦‍♂️
> 
> But after a second thought, we probably should move it to https://github.com/commitizen-tools/commitizen/blob/master/.github/workflows/docspublish.yml. otherwise, we might update the image without having them in the doc

Yeah, makes sense. The suggestion is to move all the steps on generate_cli_screenshots.yml to docspublish.yml, or somehow invoke the generate_cli_screenshots.yml after run docspublish.yml?

May I open an another issue to fix this?

**Comment by Lee-W** [comment]
> The suggestion is to move all the steps on generate_cli_screenshots.yml to docspublish.yml,
Yes

> somehow invoke the generate_cli_screenshots.yml after run docspublish.yml

nope, generate_cli_screenshots should be invoked first

> May I open an another issue to fix this?

Yep, sure :)

**Comment by marcosdotme** [comment]
> nope, generate_cli_screenshots should be invoked first


Yes, yes. I thought "before" and wrote "after" lol.

So, just to make things clear. The ideia is to delete generate_cli_screenshots.yml and move all the steps on it to docspublish.yml, and steps from generate_cli_screenshots.yml should run **before** the docspublish.yml steps. Right?

**Pull request merged**
