### PR TITLE
test(warnings): switch from the unmaintained `pytest-freezegun` to `pytest-freezer` removing warnings

### PR DESCRIPTION
**Pull request by noirbizarre**
## Description

Switch from [`pytest-freezegun`](https://pypi.org/project/pytest-freezegun/) which is not maintained anymore and stuck on a legacy `freezegun` version raising lots of warnings to [`pytest-freezer`](https://pypi.org/project/pytest-freezer/) its [maintained fork by the official `pytest-dev` github organization](https://github.com/pytest-dev/pytest-freezer) which is maintained and up to date, raises no warnings and provide typing.

## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes (N/A)

## Expected behavior

No behavior change expected.
Test should still pass but the 2662 warnings raised should have disappeared.

## Steps to Test This Pull Request

Run the test suite

## Additional context
Dependency change so the dependencies have been re-locked

### CODE REVIEW

**Review by Lee-W — APPROVED** [review]
Thanks @noirbizarre !

@woile I'm planning on merging it this week. Let me know if you want to take a deeper look. Thanks!

**Comment by Lee-W** [comment]
@noirbizarre I'm thinking maybe we could send this PR directly to main instead of v3. We could rebase it back to v3 later. What do you think?

**Comment by noirbizarre** [comment]
Except for the lockfile part, it can be sent to `main`. But in case of rebase or merge on `v3`, lockfile should be updated (they will conflict).

**Comment by Lee-W** [comment]
I think we can do the relock for main and relock again after rebasing to v3. What do you think?

**Comment by noirbizarre** [comment]
I say that because we don't have a lock yet on `main` so it will be a 2 step move:
- merge the `pyproject.toml` change only on `main`
- relock on `v3` on rebase/merge
I don't have the proper permissions to do it but I can just cherry-pick and amend the `pyproject.toml` part on `main` and keep this PR for `v3`, merge will be easier I think

**Comment by noirbizarre** [comment]
Backported in #643 but I realised that given test fixes are not on `master` tests are not passing on `master`

**Comment by Lee-W** [comment]
I just merge #643 back to main. Once main is updated, you can update your local main and rebase it back to your feature branch and than force push to this branch. Thanks for the prompt PR!

**Comment by noirbizarre** [comment]
Thanks !
Given I can't rebase `v3`, I just merged `main` into this branch so it won't conflict on later merges.

**Comment by Lee-W** [comment]
indeed. I forget that 😱 let me do so now!

**Comment by noirbizarre** [comment]
Thanks, updated.

But I think your working copy was not up to date and https://github.com/commitizen-tools/commitizen/pull/638 is missing from the rebased `v3`

**Comment by Lee-W** [comment]
yep.... do you still have the branch on your local?

**Comment by noirbizarre** [comment]
No but I just restored it on github in the PR

**Comment by Lee-W** [comment]
ah yes, we could do that. I just push that back to v3

**Comment by noirbizarre** [comment]
And this is properly rebased on `v3`

**Pull request merged**
