### PR TITLE
use error_code to do "is_signed_tag" check to avoid language issue

### PR DESCRIPTION
**Pull request by Lee-W**
## Description
as title

## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

## Expected behavior
pass all the test cases even when `LC_ALL` is set to non-English

## Steps to Test This Pull Request
1. `export LC_ALL=zh_TW.UTF-8`
2. `./script/test`

## Additional context
#542

### CODE REVIEW

**Comment by Woile** [comment]
I wonder if there's a language agnostic way of doing this, instead of forcing english into the equation 🤔

**Comment by bhelgs** [comment]
@Woile 

> I wonder if there's a language agnostic way of doing this, instead of forcing english into the equation 🤔

* `git tag -a testtag`
* `git tag -v testtag || echo $?`

The above return code is 1... so it appears the exit code is 1 for annotated tag and 0 for signed tag.

**Comment by bhelgs** [comment]
side note, `tmp_commitizen_project_with_gpg` is creating a key every time the unit tests run. I wonder if there is a way to make them temporary.

**Comment by Lee-W** [comment]
> side note, tmp_commitizen_project_with_gpg is creating a key every time the unit tests run. I wonder if there is a way to make them temporary.

Maybe we could use a context manager to remove the created key?

**Comment by gpongelli** [comment]
> @Woile
> 
> > I wonder if there's a language agnostic way of doing this, instead of forcing english into the equation 🤔
> 
>     * `git tag -a testtag`
> 
>     * `git tag -v testtag || echo $?`
> 
> 
> The above exit code is 1... so it appears the exit code is 1 for annotated tag and 0 for signed tag.


[link](https://git-scm.com/docs/git-verify-tag) `git verify-tag <tagname>` (that also print things to stdout) and then `echo $?` :
* 0 means signed tag
* 1 means not signed

**Comment by Lee-W** [comment]
Thanks @bhelgs and @gpongelli ! Let me update the code with the methods you provided!

**Comment by Lee-W** [comment]
@Woile I think this one is now ready to be reviewed 🎉

**Comment by gpongelli** [comment]
> > side note, tmp_commitizen_project_with_gpg is creating a key every time the unit tests run. I wonder if there is a way to make them temporary.
> 
> Maybe we could use a context manager to remove the created key after running testing?

PR #547  handles this ;-)

**Pull request merged**
