### PR TITLE
Lotram/customizable allowed prefixes

### PR DESCRIPTION
**Pull request by Lotram**
## Description

Related to https://github.com/commitizen-tools/commitizen/issues/672
The allowed message prefix list can now be configured. 
In particular, it can be set to an empty list, if we do not want to allow commits such as fixups.

I also fixed a typo in `.pre-commit-config.yaml` and a typing error in `commitizen/cli.py`
## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

## Expected behavior

The allowed prefix list can be configured, either using a config file, or when using the cli directly. 

## Steps to Test This Pull Request
1. `poetry shell` 
1. Run `python commitizen/cli.py check --message 'fixup!'  --allowed-prefixes 'Merge' 'Revert' 'Custom Prefix'`. It should return an error
2. Run `python commitizen/cli.py check --message "Custom Prefix random text"  --allowed-prefixes 'Merge' 'Revert' 'Custom Prefix'`. It should pass

### CODE REVIEW

**Comment by Lotram** [comment]
@woile Rebased. I removed the commit fixing the pre-commit config, as it has been fixed already

**Comment by Lotram** [comment]
@woile rebased and all checks have passed

**Review by Lee-W — APPROVED** [review]
Hi @Lotram , thanks for your contribution! Sorry for the late review. This looks great! 

@woile I'm planning on merging it soon as well. Let me know if you have other thoughts. Thanks!

**Comment by Lee-W** [comment]
close #672

**Pull request merged**
