### PR TITLE
Added conventional commits with JIRA scope.

### PR DESCRIPTION
**Pull request by Crystalix007**
This adds a new commit standard which basically enforces the scope of the conventional commit to be in the form `project-issueNumber`, in order to comply with JIRA issue tagging.

### CODE REVIEW

**Comment by Woile** [comment]
I don't know if this needs to be part of the library, looks more like a plugin, they can easily be created with [commitizen_cz_template](https://github.com/commitizen-tools/commitizen_cz_template).
We can create here a new page with a list of alternative commit rules.

What do you think @Lee-W ?

**Comment by Lee-W** [comment]
@Woile I agree with you. It seems to me we should include only the most used templates in commitizen itself to make it lightweight. Maybe we can create a awesome-commitizen-template list for it?

**Comment by Woile** [comment]
I'd link directly in the commitizen docs, like "Third party commitizen" or "Packages", or `Catalog`.

**Comment by Lee-W** [comment]
"Third party commitizen" seems to be a better one for me.

**Comment by Lee-W** [comment]
@Crystalix007 Thanks for your contribution! As discussed with @Woile, we're not planning on making it a part of commitizen. Thus, I'm closing this PR. But we're happy to add this template as a third-party commitizen in our documentation. Please let us know if you want us to add it.

**Comment by Crystalix007** [comment]
Sorry for the delay.

Is [this](https://pypi.org/project/conventional-JIRA/) okay?

The source is hosted [here](https://github.com/Crystalix007/conventional_jira).

**Comment by Woile** [comment]
Yes, that's fine, you can create a PR for the docs, create a new section: `Third party commitizen`.

**Pull request closed without merging**
