### PR TITLE
feat: Ignore fixup! & squash!

### PR DESCRIPTION
**Pull request by a5r0n**
## Description

#414 

## Checklist

- [x] Add test cases to all the changes you introduce
- [ ] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [ ] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

### CODE REVIEW

**Comment by bhelgs** [comment]
Disclaimer: I am not a maintainer. 


I wonder what happens to the changelog if you forget to rebase these out of existence. Is it (correctly) ignoring them?

**Comment by a5r0n** [comment]
the `validate_commit_message`  called only when u run `cz check` (like the pre-commit do).
so i think the changelog be not impacted.

**Review by Lee-W — APPROVED** [review]
@a5r0n Thanks for contribution! I'm good with it. @Woile could you please check whether you're good with it. Thanks!

**Comment by eldipa** [comment]
Could be possible to load the prefixes to ignore from the config file? I'm thinking that `Merge`, `Revert`, `fixup!` are quite standard but they may not fit in any project and a simple solution could load the prefixes from a file (leaving the current prefixes `Merge`, `Revert` and so on as default).

What do you think?

**Comment by Lee-W** [comment]
Hi @eldipa , I think that's a good idea! But I wish to keep this PR as it is. We could create another issue / PR for tracking the feature you mention. Thanks!

**Comment by Lee-W** [comment]
@woile I'm thinking of merging this one this week. Please let me know if we need more discussion on this one :)

**Pull request merged**
