### PR TITLE
ci: run tests on linux, mac and windows

### PR DESCRIPTION
**Pull request by Woile**

### CODE REVIEW

**Comment by Lee-W** [comment]
@Woile Do we still need this one?

**Comment by Woile** [comment]
I've rebased, let's see if it works

**Comment by Woile** [comment]
@Lee-W what do you think? I'm testing for 3.6 + the latest 2 (3.8 and 3.9). And it's working.

**Comment by Lee-W** [comment]
It's great 👍👍👍

**Pull request merged**
