### PR TITLE
feat: add major-version-zero option to support initial package development

### LINKED ISSUE #501: Breaking changes below v1 bump major version number
### Description

The SemVer spec dictates that: ["major version zero (`0.y.z`) is for initial development"](https://semver.org/#spec-item-4) and ["Version 1.0.0 defines the public API."](https://semver.org/#spec-item-5) A change during the initial development stage may be denoted as breaking, but there is little likelihood that implies the public API is stable. Bumping `0.y.z` to `1.0.0` on the first breaking change encourages a common misconception of SemVer, that major version 0 is no different from any other. More importantly, this behavior can cause unstable software to be accidentally, abruptly, and [irreversibly](https://semver.org/#spec-item-3) declared stable. It can still be helpful to consistently track which commits introduce breaking changes during initial development, and Commitizen supports a very clear syntax for doing that. If folks are not sure what `cz bump` will do, they can, of course, always run `cz bump --dry-run`. They may also use `cz bump --increment MINOR` in lieu of `cz bump` for breaking changes at major version 0, but this may be a hassle to configure when Commitizen runs in CI.

### Steps to reproduce

1. Create a new project with major version 0.
1. Run `cz commit`.
1. Select `feat`.
1. Declare the change breaking.
1. Complete the commit.
1. Run `cz bump`.

### Current behavior

`cz bump` bumps to `1.0.0`.

### Desired behavior

At major version 0, `cz bump` bumps the minor version number for all `feat` changes, breaking or otherwise. Behavior is unchanged when major version > 0.

### Screenshots

_No response_

### Environment

Commitizen Version: 2.24.0
Python Version: 3.10.4 (main, Apr  5 2022, 17:28:03) [GCC 11.2.0]
Operating System: Linux

### LINKED ISSUE #573: Typos in bump options
### Type

- [ ] Content inaccurate
- [ ] Content missing
- [X] Typo

### URL

https://commitizen-tools.github.io/commitizen/bump/#annotated_tag

### Description

Looks to me like the `pgp_sign` option has become part of the preceding source block because the closing back-ticks are missing here

https://github.com/commitizen-tools/commitizen/blob/8cb1e22d72abd855f221556f2a1c8fc0ddded109/docs/bump.md?plain=1#L363-L365

Also looks like the example is incomplete?

### PR DESCRIPTION
**Pull request by jenstroeger**
## Description

Closes #501 
Closes #573

I guess instead of the current implementation, I could have also changed the `bump_map` in the settings and not touched any of the remaining code? Please let me know which approach you’d prefer.

Still need to write tests and documentation.

## Checklist

- [ ] Add test cases to all the changes you introduce
- [X] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [X] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

## Expected behavior

As discussed in the connected issue.

## Steps to Test This Pull Request

Run the tests.

## Additional context

n/a

### CODE REVIEW

**Comment by woile** [comment]
I would prefer the `bump_map`, but I think it should be part of the ConventionalCommitCz, right? How would it look for others?

**Comment by jenstroeger** [comment]
@woile, can you please take a look at the updated PR? Is that what you had in mind?

**Comment by woile** [comment]
I'm really excited for this feature. The code looks great 💪🏻 . Few things though:

- [ ] Add tests
- [ ] Update documentation
    - cli example
    - configuration example
    - explanation and motivation for the flag
- [ ] Update `init` command (this can be introduced later)

**Comment by jenstroeger** [comment]
> I'm really excited for this feature. The code looks great 💪🏻 .

Good, then I’ll build on this change. The “major version zero” feature should apply to the [`ConventionalCommitsCz`](https://github.com/commitizen-tools/commitizen/blob/a9873d1cc5a229f97f7f775511cecffa8288e071/commitizen/cz/conventional_commits/conventional_commits.py#L30) class only, yes? Not the [`custom` and `jira`](https://github.com/commitizen-tools/commitizen/tree/master/commitizen/cz) variants?

> Few things though:

Yup!

I see heaps of tests failing wrt. signing commits—is there anything in particular I need to set up to run these tests? The [contributing.md](https://github.com/commitizen-tools/commitizen/blob/master/docs/contributing.md) might miss some information?

**Comment by woile** [comment]
> Good, then I’ll build on this change. The “major version zero” feature should apply to the [ConventionalCommitsCz](https://github.com/commitizen-tools/commitizen/blob/a9873d1cc5a229f97f7f775511cecffa8288e071/commitizen/cz/conventional_commits/conventional_commits.py#L30) class only, yes? Not the [custom and jira](https://github.com/commitizen-tools/commitizen/tree/master/commitizen/cz) variants?

Indeed, we just make the setting available, this one anyone can use it, but to our rules, it only fits with conventional commits.

> I see heaps of tests failing wrt. signing commits—is there anything in particular I need to set up to run these tests? The [contributing.md](https://github.com/commitizen-tools/commitizen/blob/master/docs/contributing.md) might miss some information?

I'm not aware if there's anything extra required @Lee-W ? Try rebasing to latest

**Comment by Lee-W** [comment]
@woile  I don't think there's extra setting needed. One thing kinda bugs me is the default git branch name. If you set it to main, it might break some tests. 
@jenstroeger Could you please share the error message you encounter so that we could know what might be the issue? Thanks1

**Comment by jenstroeger** [comment]
> @jenstroeger Could you please share the error message you encounter so that we could know what might be the issue? Thanks1

The problem is that my global `git` configuration contains
```
> git config --global --list
commit.gpgsign=true
gpg.program=/opt/local/bin/gpg
```
which cause this issue during tests:
```
E           commitizen.exceptions.CommitError: error: gpg failed to sign the data
E           fatal: failed to write commit object
```
Setting it to `false` (temporarily) took care of it.

**Comment by jenstroeger** [comment]
@Lee-W @woile can you please take a look?

**Review by woile — APPROVED** [review]
LGTM @Lee-W feel free to merge if it's ok for you

**Review by Lee-W — APPROVED** [review]

**Comment by jenstroeger** [comment]
Oh wow, already merged and shipped! All good with the code? Thanks guys ☺️

**Pull request merged**
