### PR TITLE
style: move codespell configuration to pyproject.toml

### PR DESCRIPTION
**Pull request by yarikoptic**
## Description

So people could just run "codespell" without pre-commit and have centralized configuration for tools (the others are already in pyproject.toml)

## Checklist

- [N/A] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test

I did ;) 
```shell
❯ ./scripts/format
+ poetry run python -m ruff format commitizen tests
/home/yoh/venvs/dev3.11/bin/python: No module named ruff
❯ ./scripts/test
ImportError while loading conftest '/home/yoh/proj/misc/commitizen/tests/conftest.py'.
tests/conftest.py:10: in <module>
    from pytest_mock import MockerFixture
E   ModuleNotFoundError: No module named 'pytest_mock'
```

- [x] Test the changes on the local machine manually
- [ ] Update the documentation for the changes

### CODE REVIEW

**Comment by Lee-W** [comment]
@yarikoptic You'll need to run `poetry install` first before running `./scripts/test` and `./scripst/format`

**Comment by Lee-W** [comment]
@yarikoptic According to the CI, it seems `poetry.lock` is not ignored in this setup. Could you please take a look? Thanks!

**Comment by yarikoptic** [comment]
That's done, will need to fix up commit message now when wake up

**Comment by yarikoptic** [comment]
done, green now

**Review by Lee-W — APPROVED** [review]

**Pull request merged**
