### PR TITLE
feat(template): allow to override the template from cli, configuration and plugins

### PR DESCRIPTION
**Pull request by Skeen**
Attempted rebase of https://github.com/commitizen-tools/commitizen/pull/645

### CODE REVIEW

**Comment by Lee-W** [comment]
Thanks for helping out! I'll take a look this or next week. Looking forward to merging this one 💪

**Comment by woile** [comment]
me too, I'll try to take a look at it this week, thanks

**Comment by BuSHari** [comment]
Hi,
This is an needed feature that i would like to finally use, thanks for the effort.
Is there any update on this merge?

**Comment by Lee-W** [comment]
> Hi, This is an needed feature that i would like to finally use, thanks for the effort. Is there any update on this merge?

both maintainers have been out of bandwidth recently and probably don't have the energy to fully review it (even though we're really excited about this as well)

**Comment by Skeen** [comment]
Closed in favor of https://github.com/commitizen-tools/commitizen/pull/645

**Pull request closed without merging**
