### PR TITLE
docs(README): add "pre-commit install --hook-type commit-msg" command

### PR DESCRIPTION
**Pull request by Lee-W**
… to pre-commit section

(Thanks for sending a pull request! Please fill in the following content to let us know better about this change.)

## Types of changes
Please put an `x` in the box that applies

- [x] **Documentation Update**
- [x] **CI Update**

## Description
docs(README): add "pre-commit install --hook-type commit-msg" command
ci: rename scripts/reformat as scripts/format

## Checklist:
- [ ] Add test cases to all the changes you introduce
- [x] Run `./script/reformat` and `./script/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

## Steps to Test This Pull Request
None

## Expected behavior
None

## Related Issue
If applicable, reference to the issue related to this pull request.

## Additional context
Add any other context or screenshots about the pull request here.

### CODE REVIEW

**Comment by Woile** [comment]
Should we add pre-commit as dev-dependecy?

**Comment by altusgerona** [comment]
Having dev dependencies on poetry really makes me wanna ditch pip.

**Comment by Lee-W** [comment]
It seems we'll need to change the lowest python version from 3.6 to 3.6.1 to add pre-commit as dev deps. If that's ok, I can add it.

**Comment by Woile** [comment]
Nice!

**Pull request merged**
