### PR TITLE
Homebrew Update

### PR DESCRIPTION
**Pull request by harens**
## Description
Following the addition of commitizen to homebrew, I've updated the docs and added a Github Action.

The workflow depends on a [Personal Access Token](https://github.com/settings/tokens/new?scopes=public_repo) being made available for it.

## Checklist

- [ ] Add test cases to all the changes you introduce
- [ ] Run `./script/format` and `./script/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

## Expected behavior
Whenever a release is published, a PR should be sent to update the Homebrew formula.

## Steps to Test This Pull Request
N/A

## Additional context
Closes https://github.com/commitizen-tools/commitizen/issues/256

Github Action based on https://github.com/commitizen-tools/commitizen/issues/256#issuecomment-704182520 and [nef's workflow](https://github.com/bow-swift/nef/blob/master/.github/workflows/bump-formula.yml).

An example of nef's workflow being run successfully can be found [here](https://github.com/bow-swift/nef/actions/runs/181470176)

### CODE REVIEW

**Comment by harens** [comment]
Error seems unrelated:

```
commitizen/commands/init.py:50: error: Argument "choices" to "select" has incompatible type "List[str]"; expected "List[Union[str, Choice, Dict[str, Any]]]"
```

**Comment by Lee-W** [comment]
I'm still trying to understand this issue. It seems related to https://mypy.readthedocs.io/en/stable/generics.html#variance-of-generic-types

**Comment by Woile** [comment]
I think it's related to questionary, but not sure.
we could skip linting there by adding a comment: `# type: ignore`
When I have more time I'll check again

**Comment by Woile** [comment]
I've opened a ticket on mypy https://github.com/python/mypy/issues/9555

**Comment by Lee-W** [comment]
I think that is not actually a bug but rather how mypy is designed.
https://github.com/python/mypy/issues/3351


The error message of this issue is as followed.

```
commitizen/commands/init.py:50: error: Argument "choices" to "select" has incompatible type "List[str]"; expected "List[Union[str, Choice, Dict[str, Any]]]"
commitizen/commands/init.py:50: note: "List" is invariant -- see http://mypy.readthedocs.io/en/latest/common_issues.html#variance
commitizen/commands/init.py:50: note: Consider using "Sequence" instead, which is covariant
commitizen/commands/init.py:82: error: Argument "choices" to "select" has incompatible type "Optional[List[str]]"; expected "List[Union[str, Choice, Dict[str, Any]]]"
```

In [mypy doc](https://mypy.readthedocs.io/en/latest/common_issues.html#variance), it explains how we might be able to solve this problem. However, the type annotation is located in [questionary](https://github.com/tmbo/questionary/blob/master/questionary/prompts/select.py#L18)

If questionary uses `Sequence[Union[Text, Choice, Dict[Text, Any]]]` instead, we might not encounter this problem.

As for line 82, it's probably an error I created. I dicsussed it with the author or #279 offline, we'll fix that one.

**Comment by Woile** [comment]
Can u rebase the PR? Thanks

**Comment by harens** [comment]
Hopefully that should do it, although let me know if it didn't. I'm happy to squash my commits if necessary, although I left them as two separate ones since one's for the docs and the other is for the workflow.

(I like the summary above ☝by the way)

**Comment by Lee-W** [comment]
Left them as separate commits is great! Thanks for your great work! Let's merge it 😃

**Pull request merged**
