### PR TITLE
feat(bump): support prereleases with a start offset

### PR DESCRIPTION
**Pull request by ckagerer**
This PR solves #613 

For special cases it may be necessary that prereleases cannot start with a 0, because the single characters are encoded in bytes. Here, consistent with the location for bugfixes, a 0 in the byte is interpreted as a release version. Therefore this commit introduces a generic option to change the start of the prerelease and also adapt it to such circumstances.

EXAMPLES

Previously:
0.3.0 -> PATCH beta-> 0.3.1b0

Now (with offset 0 == default):
0.3.0 -> PATCH beta-> 0.3.1b0

Now (with offset 1):
0.3.0 -> PATCH beta-> 0.3.1b1

## Checklist

- [x] Add test cases to all the changes you introduce
- [x] Run `./scripts/format` and `./scripts/test` locally to ensure this change passes linter check and test
- [x] Test the changes on the local machine manually
- [x] Update the documentation for the changes

### CODE REVIEW

**Review by Lee-W — COMMENTED** [review]
Hi @ckagerer , thanks for your contribution and sorry for taking so long. The code looks good to me 🙌 But we might need your help to add some documentation and rebase the latest changes from the master branch.

**Comment by ckagerer** [comment]
Hi @Lee-W,
Thanks for your feedback and initial review.

I have rebased the latest master branch to my feature branch.

Where do you expect the documentation to be?
More in the code or is there more documentation?

Best regards
Christian

**Comment by Lee-W** [comment]
Hi @ckagerer thanks for the prompt update. I think we'll need to add the usage in https://github.com/commitizen-tools/commitizen/blob/master/docs/bump.md so that users know how to use

**Comment by ckagerer** [comment]
@Lee-W
Sure, I will be happy if my PR is integrated :)

I have already extended the documentation in config.md.

Should I also include a command line argument, or is it enough just to use the configuration?

**Comment by Lee-W** [comment]
@ckagerer It would be better if you could add the command line argument. Also, I notice we'll have to update the output of `cz bump --help` in https://github.com/commitizen-tools/commitizen/blob/master/docs/bump.md

**Comment by ckagerer** [comment]
@Lee-W
Command line argument has been added and I have extended the documentation.
What do you think?

**Comment by Lee-W** [comment]
Hi @ckagerer it looks great! I think our last step is to taking care of the CI failure.

**Comment by ckagerer** [comment]
Hey @Lee-W 

Oh yes, I have ignored this so far because one of the unit tests fails locally on the master.

It seems to go wrong when installing with pip. Any experience with this?

I can try a poetry update to see if that helps.

**Comment by ckagerer** [comment]
No, there are no updates at all.
It fails with the "poetry install" but I have no idea why.

**Comment by Lee-W** [comment]
Do you have the error message?

**Comment by ckagerer** [comment]
@Lee-W 

I think I read the message completely wrong :)

I ran the format script again and it was one line short. Now it should fit :)

**Pull request merged**
